options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Install dependencies
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci
        npm install -g @angular/cli

  # 2️⃣ Build Angular app with production fixes
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run build:prod

  # 3️⃣ Deploy to Firebase Hosting (install firebase-tools here)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project $PROJECT_ID
