options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Build the Angular app (production mode)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci --legacy-peer-deps
        npm install -g @angular/cli
        npm run build -- --configuration=production

  # 2️⃣ Deploy to Firebase Hosting (production target)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting:prod --project $PROJECT_ID
