options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1️⃣ Install dependencies and build in a single step
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm ci --legacy-peer-deps
        npm install -g @angular/cli
        npm run build:prod

  # 2️⃣ Deploy to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project $PROJECT_ID
