// AUTO-GENERATED FILE. DO NOT EDIT.
// This file was generated by tools/write-version.js
// Commit: 6e745c3, Branch: main, Build: 125

export const APP_VERSION = "0.1.1";
export const PREVIOUS_COMMIT_HASH = "6e745c3";
