// AUTO-GENERATED FILE. DO NOT EDIT.
// This file was generated by tools/write-version.js
// Commit: 454270e, Branch: nutritionix, Build: 145

export const APP_VERSION = "0.3.3-nutritionix.145+454270e";
export const PREVIOUS_COMMIT_HASH = "454270e";
