// AUTO-GENERATED FILE. DO NOT EDIT.
// This file was generated by tools/write-version.js
// Commit: 9c3db1e, Branch: main, Build: 279

export const APP_VERSION = "0.8.8";
export const PREVIOUS_COMMIT_HASH = "9c3db1e";
